[package]
name = "ksunami"
version = "0.1.0"
edition = "2021"
authors = ["Ivan De Marino <detronizator@gmail.com>", "Kafkesc <https://github.com/kafkesc>"]
repository = "https://github.com/kafkesc/ksunami"
description = "Continuosly Produce a wave of Kafka Records."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flo_curves = "0.6.1"
clap = { version = "4.0.14", features = ["derive", "deprecated", "env", "wrap_help"] }
log = "0.4.17"
env_logger = "0.9.1"
rdkafka = { version = "0.28.0", features = ["ssl-vendored", "gssapi-vendored", "libz-static", "zstd"] }
tokio = { version = "1", features = ["full"] }
rand = "0.8.5"
futures = "0.3.25"
