[package]
name = "ksunami"
version = "0.1.4"
edition = "2021"
authors = ["Ivan De Marino <detronizator@gmail.com>", "Kafkesc <https://github.com/kafkesc>"]
repository = "https://github.com/kafkesc/ksunami"
homepage = "https://github.com/kafkesc/ksunami"
description = "Produce constant, configurable, cyclical waves of Kafka Records"
license = "Apache-2.0"
keywords = ["kafka", "workload", "testing", "performance", "developer-tools"]
categories = ["command-line-utilities", "development-tools"]
exclude = [
    ".github/",
    ".gitignore",
    "images/*",
]

[dependencies]
flo_curves = "0.6.1"
clap = { version = "4.0.26", features = ["derive", "deprecated", "env", "wrap_help"] }
log = "0.4.17"
env_logger = "0.9.3"
rdkafka = { version = "0.29.0", features = ["ssl-vendored", "gssapi-vendored", "libz-static"] }
tokio = { version = "1.22.0", features = ["rt", "rt-multi-thread", "time", "sync", "macros"] }
rand = "0.8.5"
futures = "0.3.25"
ctrlc = { version = "3.2.3", features = ["termination"] }
