[package]
name = "ksunami"
version = "0.1.0"
edition = "2021"
authors = ["Ivan De Marino <detronizator@gmail.com>", "Kafkesc <https://github.com/kafkesc>"]
repository = "https://github.com/kafkesc/ksunami"
description = "Continuosly Produce a wave of Kafka Records."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flo_curves = "0.6.1"
clap = { version = "4.0.14", features = ["derive", "deprecated", "env", "wrap_help"] }
