[target.aarch64-unknown-linux-gnu]
pre-build = ["dpkg --add-architecture arm64 && apt update && apt install -y libssl-dev libsasl2-dev"]

[target.i686-unknown-linux-gnu]
pre-build = ["dpkg --add-architecture i386 && apt update && apt install -y libssl-dev libsasl2-dev"]

[target.x86_64-unknown-linux-gnu]
pre-build = ["dpkg --add-architecture amd64 && apt update && apt install -y libssl-dev libsasl2-dev"]

[target.arm-unknown-linux-gnueabihf]
pre-build = ["dpkg --add-architecture armhf && apt update && apt install -y libssl-dev libsasl2-dev"]

[target.arm-unknown-linux-musleabihf]
pre-build = ["dpkg --add-architecture armhf && apt update && apt install -y libssl-dev libsasl2-dev"]

[target.i686-unknown-linux-musl]
pre-build = ["dpkg --add-architecture i386 && apt update && apt install -y libssl-dev libsasl2-dev"]

[target.x86_64-unknown-linux-musl]
pre-build = ["dpkg --add-architecture amd64 && apt update && apt install -y libssl-dev libsasl2-dev"]
