#[target.aarch64-unknown-linux-gnu]
#pre-build = ["""
#    apt-get update && apt install -y \
#        cmake build-essential make pkg-config \
#        clang llvm \
#        gcc-x86-64-linux-gnu g++-x86-64-linux-gnu \
#        gcc-aarch64-linux-gnu g++-aarch64-linux-gnu \
#        libsasl2-dev libssl-dev libzstd-dev zlib1g-dev
#    """]
#
#[target.x86_64-unknown-linux-gnu]
#pre-build = ["apt-get update && apt install -y cmake build-essential make pkg-config libsasl2-dev libssl-dev libzstd-dev zlib1g-dev clang llvm"]
