name: Build + Test

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - 'images/*'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - 'images/*'

env:
  CARGO_TERM_COLOR: always

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
    - name: Build dependencies
      run: sudo apt install -y libsasl2-dev
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build
    - name: Test
      run: cargo test
