name: CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - 'images/*'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - 'images/*'

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Build dependencies
      run: sudo apt install -y libsasl2-dev
    - name: Check-out code
      uses: actions/checkout@v3
    - name: Build code
      run: cargo build
    - name: Run tests
      run: cargo test
