name: Creates.io Publish

on:
  push:
    tags: [ "v[0-9]+.[0-9]+.[0-9]+*" ]

env:
  CARGO_TERM_COLOR: always
  CRATES_TOKEN: ${{ secrets.CRATES_IO_PUBLISH_TOKEN }}

jobs:
  publish:
    name: Publish

    runs-on: ubuntu-latest

    steps:
      - name: Check-out
        uses: actions/checkout@v3

      - name: Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Cargo publish
        run: cargo publish --locked --token ${CRATES_IO_PUBLISH_TOKEN}
