name: Publish Crate

on:
  # This workflow is designed to be triggered, when a tag is pushed against "main" branch.workflow_call:
  # Tags must be of the format "vX.Y.Z" or "vX.Y.Z-SOMETHING".
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

env:
  CARGO_TERM_COLOR: always

jobs:
  publish-crates_io:
    name: Publish to crates.io (${{ github.ref_name }})

    runs-on: ubuntu-latest

    steps:

      - name: Dependencies
        run: |
          sudo apt update
          sudo apt install -y libsasl2-dev

      - name: Check-out
        uses: actions/checkout@v4

      - name: Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Cargo publish
        run: cargo publish --locked
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_PUBLISH_TOKEN }}

  publish-hub_docker_com:
    name: Publish to hub.docker.com
    needs:
      - publish-crates_io
    uses: ./.github/workflows/hub.docker.com-publish.yml
    with:
      release-version: ${{ github.ref_name }}
    secrets:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-password: ${{ secrets.DOCKERHUB_TOKEN }}