name: GitHub Release

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
    tags: [ "v[0-9]+.[0-9]+.[0-9]+*" ]
  workflow_dispatch:

jobs:
  release:
    name: GH Release
    runs-on: ${{ matrix.runs_on }}
    continue-on-error: ${{ matrix.experimental}}
    strategy:
      fail-fast: false
      matrix:
        include:
#          # Linux
#          - target: x86_64-unknown-linux-gnu
#            arch: x86_64
#            runs_on: ubuntu-latest
#            use_cross: false
#            experimental: true
#          # macOS
#          - target: x86_64-apple-darwin
#            arch: x86_64
#            runs_on: macos-latest
#            use_cross: false
#            experimental: true
          # Windows
          - target: x86_64-pc-windows-msvc
            arch: x86_64
            runs_on: windows-2019
            use_cross: false
            experimental: true
    steps:
      - name: Check-out
        uses: actions/checkout@v2

      - name: Dependencies (Linux)
        if: ${{ matrix.runs_on == 'ubuntu-latest' }}
        run: sudo apt install -y libsasl2-dev

#      - name: VS C++ Build Tools (Windows)
#        if: ${{ matrix.runs_on == 'windows-latest' }}
#        run: |
#          choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.CMake.Project --add Microsoft.VisualStudio.Component.VC.CoreIde --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --add Microsoft.VisualStudio.Component.Windows10SDK.19041 --add Microsoft.Component.VC.Runtime.OSSupport --add Microsoft.VisualStudio.Component.VC.CLI.Support --add Microsoft.VisualStudio.Component.VC.Llvm.Clang --add Microsoft.VisualStudio.Component.VC.Llvm.ClangToolset --add Microsoft.VisualStudio.Component.VC.Modules.x86.x64 --add Microsoft.VisualStudio.ComponentGroup.NativeDesktop.Llvm.Clang"

      - name: VS C++ Build Tools (Windows)
        if: ${{ startsWith(matrix.runs_on, 'windows') }}
        run: >-
          choco install visualstudio2019buildtools --package-parameters "
            --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64
            --add Microsoft.VisualStudio.Component.Windows10SDK.19041
          "

      - name: Expose MS Visual C++ CMD (Windows)
        if: ${{ startsWith(matrix.runs_on, 'windows') }}
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
          vsversion: 2019

      - name: Toolchain ${{ matrix.target }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          profile: minimal
          override: true
          default: true

      - name: Build ${{ matrix.target }}
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.use_cross }}
          command: build
          args: --release --target=${{ matrix.target }}

      - name: Show
        run: |
          pwd
          ls -l target/
          ls -l target/${{ matrix.target }}/release
          file target/${{ matrix.target }}/release/ksunami
